### ISSUE TITLE
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF ModuleNotFoundError: No module named 'krahenbuhl2013'

### ISSUE THREAD

**Issue by monajalal** [paulu/material-seg#2]
We are not sure how to fix this in Anaconda Python 3.6.3. Can you please guide or give us any sort of hint:

```
[jalal@goku material-seg]$ python demo.py images/1189.jpg
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
running build_ext
python -c "import krahenbuhl2013"
Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "minc_dataset/material-seg/densecrf_matclass/densecrf.py", line 13, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ModuleNotFoundError: No module named 'krahenbuhl2013'
[jalal@goku material-seg]$ cd densecrf_matclass/krahenbuhl2013/
[jalal@goku krahenbuhl2013]$ ls
build    __init__.py         krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so  Makefile     __pycache__  src
include  krahenbuhl2013.cpp  krahenbuhl2013.pyx                              memory-test  setup.py
```

**Comment by paulu** [comment]
Try renaming krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so to krahenbuhl2013.so

**Comment by monajalal** [comment]
it didn't work:

```
[jalal@goku krahenbuhl2013]$ mv krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so krahenbuhl2013.so
[jalal@goku krahenbuhl2013]$ ls -ltra
total 8932
-rw-r--r--. 1 jalal cs-grad     130 Nov 27 18:21 Makefile
-rw-r--r--. 1 jalal cs-grad       0 Nov 27 18:21 __init__.py
drwxr-xr-x. 2 jalal cs-grad     175 Nov 27 18:21 include
-rw-r--r--. 1 jalal cs-grad      44 Nov 27 18:21 .gitignore
-rw-r--r--. 1 jalal cs-grad    3453 Nov 27 18:21 krahenbuhl2013.pyx
drwxr-xr-x. 2 jalal cs-grad      81 Nov 27 18:21 memory-test
drwxr-xr-x. 2 jalal cs-grad     265 Nov 27 18:21 src
-rw-r--r--. 1 jalal cs-grad     848 Nov 27 18:30 setup.py
-rw-r--r--. 1 jalal cs-grad  964415 Nov 27 18:30 krahenbuhl2013.cpp
drwxr-xr-x. 3 jalal cs-grad      43 Nov 27 18:30 build
-rwxr-xr-x. 1 jalal cs-grad 8152416 Nov 27 18:37 krahenbuhl2013.so
drwxr-xr-x. 2 jalal cs-grad      37 Nov 27 19:05 __pycache__
drwxr-xr-x. 6 jalal cs-grad    4096 Nov 27 19:15 ..
drwxr-xr-x. 7 jalal cs-grad    4096 Nov 27 20:13 .

[jalal@goku material-seg]$ python demo.py images/1189.jpg
Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "minc_dataset/material-seg/densecrf_matclass/densecrf.py", line 13, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ModuleNotFoundError: No module named 'krahenbuhl2013'
```

**Comment by paulu** [comment]
The problem could be that the extension module is not building properly. Check these steps for errors:

1. cd densecrf_matclass/krahenbuhl2013
2. make clean
3. make
4. python2
\>\>\> import krahenbuhl2013
\>\>\>


I tested this with Cython==0.26.1 and Python 2.7.6. Also, from your previous issue it seems that your "python" is Python 3. My scripts expect "python" to be Python 2. This could be the source of many problems.

**Comment by monajalal** [comment]
Thanks a lot for your great insights. I tried your sequence of commands but I still can't import. I will work more on this later and will report if I could fix the problem.

```
[jalal@goku densecrf_matclass]$ cd krahenbuhl2013/
[jalal@goku krahenbuhl2013]$ make clean
rm -rf build/ krahenbuhl2013.so krahenbuhl2013.cpp
[jalal@goku krahenbuhl2013]$ make
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
Compiling krahenbuhl2013.pyx because it changed.
[1/1] Cythonizing krahenbuhl2013.pyx
running build_ext
building 'krahenbuhl2013' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c krahenbuhl2013.cpp -o build/temp.linux-x86_64-3.6/krahenbuhl2013.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from krahenbuhl2013.cpp:530:
/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf.cpp -o build/temp.linux-x86_64-3.6/src/densecrf.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/labelcompatibility.cpp -o build/temp.linux-x86_64-3.6/src/labelcompatibility.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/pairwise.cpp -o build/temp.linux-x86_64-3.6/src/pairwise.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/permutohedral.cpp -o build/temp.linux-x86_64-3.6/src/permutohedral.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/unary.cpp -o build/temp.linux-x86_64-3.6/src/unary.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/util.cpp -o build/temp.linux-x86_64-3.6/src/util.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/objective.cpp -o build/temp.linux-x86_64-3.6/src/objective.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf_wrapper.cpp -o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -B /scratch/sjn/anaconda/compiler_compat -L/scratch/sjn/anaconda/lib -Wl,-rpath=/scratch/sjn/anaconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/krahenbuhl2013.o build/temp.linux-x86_64-3.6/src/densecrf.o build/temp.linux-x86_64-3.6/src/labelcompatibility.o build/temp.linux-x86_64-3.6/src/pairwise.o build/temp.linux-x86_64-3.6/src/permutohedral.o build/temp.linux-x86_64-3.6/src/unary.o build/temp.linux-x86_64-3.6/src/util.o build/temp.linux-x86_64-3.6/src/objective.o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o -L/scratch/sjn/anaconda/lib -lpython3.6m -o /scratch2/cs542/minc_dataset/material-seg/densecrf_matclass/krahenbuhl2013/krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so
python -c "import krahenbuhl2013"
[jalal@goku krahenbuhl2013]$ python -c "import krahenbuhl2013"
[jalal@goku krahenbuhl2013]$ cd ..
[jalal@goku densecrf_matclass]$ cd ..
[jalal@goku material-seg]$ ls
demo.py                            deploy-googlenet_full_conv_no_pooling.prototxt  matclass       requirements.txt
densecrf_matclass                  images                                          netsurgery.py  results
deploy-alexnet_full_conv.prototxt  imageutils.py                                   README.md
[jalal@goku material-seg]$ python demo.py images/1189.jpg
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
running build_ext
python -c "import krahenbuhl2013"
Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch2/cs542/minc_dataset/material-seg/densecrf_matclass/densecrf.py", line 13, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ModuleNotFoundError: No module named 'krahenbuhl2013'
[jalal@goku material-seg]$
```
Additionally, I changed the name for .so to what you said earlier and didn't had any effect:

```
[jalal@goku densecrf_matclass]$ cd krahenbuhl2013/
[jalal@goku krahenbuhl2013]$ ls -ltra
total 8928
-rw-r--r--. 1 jalal cs-grad     130 Nov 27 18:21 Makefile
-rw-r--r--. 1 jalal cs-grad       0 Nov 27 18:21 __init__.py
drwxr-xr-x. 2 jalal cs-grad     175 Nov 27 18:21 include
-rw-r--r--. 1 jalal cs-grad      44 Nov 27 18:21 .gitignore
-rw-r--r--. 1 jalal cs-grad    3453 Nov 27 18:21 krahenbuhl2013.pyx
drwxr-xr-x. 2 jalal cs-grad      81 Nov 27 18:21 memory-test
drwxr-xr-x. 2 jalal cs-grad     265 Nov 27 18:21 src
-rw-r--r--. 1 jalal cs-grad     848 Nov 27 18:30 setup.py
drwxr-xr-x. 2 jalal cs-grad      37 Nov 27 19:05 __pycache__
drwxr-xr-x. 6 jalal cs-grad    4096 Nov 27 19:15 ..
-rw-r--r--. 1 jalal cs-grad  960289 Nov 27 21:10 krahenbuhl2013.cpp
drwxr-xr-x. 3 jalal cs-grad      43 Nov 27 21:10 build
drwxr-xr-x. 7 jalal cs-grad    4096 Nov 27 21:10 .
-rwxr-xr-x. 1 jalal cs-grad 8151440 Nov 27 21:10 krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so
[jalal@goku krahenbuhl2013]$ mv krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so krahenbuhl2013.so
[jalal@goku krahenbuhl2013]$ cd ../..
[jalal@goku material-seg]$ python demo.py images/1189.jpg
Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch2/cs542/minc_dataset/material-seg/densecrf_matclass/densecrf.py", line 13, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ModuleNotFoundError: No module named 'krahenbuhl2013'
```

I guess this might be a path problem:

```
[jalal@goku krahenbuhl2013]$ python -c "from krahenbuhl2013.krahenbuhl2013 import DenseCRF"
[jalal@goku krahenbuhl2013]$ cd ..
[jalal@goku densecrf_matclass]$ python -c "from krahenbuhl2013.krahenbuhl2013 import DenseCRF"
[jalal@goku densecrf_matclass]$ cd ..
[jalal@goku material-seg]$ python -c "from krahenbuhl2013.krahenbuhl2013 import DenseCRF"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'krahenbuhl2013'
```

**Comment by paulu** [comment]
I added more details in requirements.txt and README.md on my configuration.
