### ISSUE TITLE
ImportError: dynamic module does not define init function (initkrahenbuhl2013)

### ISSUE THREAD

**Issue by monajalal** [paulu/material-seg#4]
So, I got the code again fresh from repo, and ran it with Python 2. It still has library linking problem with Python 2. Can you please have a look and suggest a fix? 
I also followed your previous suggestion for "make clean" and "make" in krahenbuhl folder. 

```
[jalal@goku material-seg]$ /scratch/sjn-p2/anaconda/anaconda2/bin/python demo.py images/1189.jpg
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'densecrf_matclass.krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
Compiling krahenbuhl2013.pyx because it changed.
[1/1] Cythonizing krahenbuhl2013.pyx
running build_ext
building 'krahenbuhl2013' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c krahenbuhl2013.cpp -o build/temp.linux-x86_64-3.6/krahenbuhl2013.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from krahenbuhl2013.cpp:530:
/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf.cpp -o build/temp.linux-x86_64-3.6/src/densecrf.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/labelcompatibility.cpp -o build/temp.linux-x86_64-3.6/src/labelcompatibility.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/pairwise.cpp -o build/temp.linux-x86_64-3.6/src/pairwise.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/permutohedral.cpp -o build/temp.linux-x86_64-3.6/src/permutohedral.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/unary.cpp -o build/temp.linux-x86_64-3.6/src/unary.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/util.cpp -o build/temp.linux-x86_64-3.6/src/util.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/objective.cpp -o build/temp.linux-x86_64-3.6/src/objective.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf_wrapper.cpp -o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -B /scratch/sjn/anaconda/compiler_compat -L/scratch/sjn/anaconda/lib -Wl,-rpath=/scratch/sjn/anaconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/krahenbuhl2013.o build/temp.linux-x86_64-3.6/src/densecrf.o build/temp.linux-x86_64-3.6/src/labelcompatibility.o build/temp.linux-x86_64-3.6/src/pairwise.o build/temp.linux-x86_64-3.6/src/permutohedral.o build/temp.linux-x86_64-3.6/src/unary.o build/temp.linux-x86_64-3.6/src/util.o build/temp.linux-x86_64-3.6/src/objective.o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o -L/scratch/sjn/anaconda/lib -lpython3.6m -o /scratch/mona/download/cs542/material-seg/densecrf_matclass/krahenbuhl2013/krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so
python -c "import krahenbuhl2013"
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch/mona/download/cs542/material-seg/densecrf_matclass/densecrf.py", line 6, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ImportError: No module named krahenbuhl2013
[jalal@goku material-seg]$ cd densecrf_matclass/
[jalal@goku densecrf_matclass]$ cd krahenbuhl2013/
[jalal@goku krahenbuhl2013]$ make clean
rm -rf build/ krahenbuhl2013.so krahenbuhl2013.cpp
[jalal@goku krahenbuhl2013]$ make
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'densecrf_matclass.krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
Compiling krahenbuhl2013.pyx because it changed.
[1/1] Cythonizing krahenbuhl2013.pyx
running build_ext
building 'krahenbuhl2013' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c krahenbuhl2013.cpp -o build/temp.linux-x86_64-3.6/krahenbuhl2013.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from krahenbuhl2013.cpp:530:
/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf.cpp -o build/temp.linux-x86_64-3.6/src/densecrf.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/labelcompatibility.cpp -o build/temp.linux-x86_64-3.6/src/labelcompatibility.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/pairwise.cpp -o build/temp.linux-x86_64-3.6/src/pairwise.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/permutohedral.cpp -o build/temp.linux-x86_64-3.6/src/permutohedral.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/unary.cpp -o build/temp.linux-x86_64-3.6/src/unary.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/util.cpp -o build/temp.linux-x86_64-3.6/src/util.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/objective.cpp -o build/temp.linux-x86_64-3.6/src/objective.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/python3.6/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/python3.6m -c src/densecrf_wrapper.cpp -o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -B /scratch/sjn/anaconda/compiler_compat -L/scratch/sjn/anaconda/lib -Wl,-rpath=/scratch/sjn/anaconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/krahenbuhl2013.o build/temp.linux-x86_64-3.6/src/densecrf.o build/temp.linux-x86_64-3.6/src/labelcompatibility.o build/temp.linux-x86_64-3.6/src/pairwise.o build/temp.linux-x86_64-3.6/src/permutohedral.o build/temp.linux-x86_64-3.6/src/unary.o build/temp.linux-x86_64-3.6/src/util.o build/temp.linux-x86_64-3.6/src/objective.o build/temp.linux-x86_64-3.6/src/densecrf_wrapper.o -L/scratch/sjn/anaconda/lib -lpython3.6m -o /scratch/mona/download/cs542/material-seg/densecrf_matclass/krahenbuhl2013/krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so
python -c "import krahenbuhl2013"
[jalal@goku krahenbuhl2013]$ ls
build    __init__.py   krahenbuhl2013.cpp                              krahenbuhl2013.pyx  memory-test  src
include  __init__.pyc  krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so  Makefile            setup.py
[jalal@goku krahenbuhl2013]$ cd ..
[jalal@goku densecrf_matclass]$ cd ..
[jalal@goku material-seg]$ /scratch/sjn-p2/anaconda/anaconda2/bin/python demo.py images/1189.jpg
python setup.py build_ext -i
Warning: Extension name 'krahenbuhl2013' does not match fully qualified name 'densecrf_matclass.krahenbuhl2013.krahenbuhl2013' of 'krahenbuhl2013.pyx'
running build_ext
python -c "import krahenbuhl2013"
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch/mona/download/cs542/material-seg/densecrf_matclass/densecrf.py", line 6, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ImportError: No module named krahenbuhl2013
[jalal@goku material-seg]$ python -c "import krahenbuhl2013"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'krahenbuhl2013'
[jalal@goku material-seg]$ cd densecrf_matclass/
[jalal@goku densecrf_matclass]$ python -c "import krahenbuhl2013"
[jalal@goku densecrf_matclass]$ cd ..
[jalal@goku material-seg]$ 

```

After I changed the name for the .so file, I get this error:

```
[jalal@goku krahenbuhl2013]$ mv krahenbuhl2013.cpython-36m-x86_64-linux-gnu.so krahenbuhl2013.so
[jalal@goku material-seg]$ /scratch/sjn-p2/anaconda/anaconda2/bin/python demo.py images/1189.jpg
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch/mona/download/cs542/material-seg/densecrf_matclass/densecrf.py", line 6, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ImportError: dynamic module does not define init function (initkrahenbuhl2013)
```
```
$ /scratch/sjn-p2/anaconda/anaconda2/bin/python --version
Python 2.7.14 :: Anaconda custom (64-bit)
```

```
$ uname -a
Linux goku.bu.edu 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

[jalal@goku krahenbuhl2013]$ file krahenbuhl2013.so
krahenbuhl2013.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

What do you think would be the fix for the last error? 
Thanks for having a look.

**Comment by paulu** [comment]
If you read the first line of the build output you'll see that it is compiling against Python 3 headers and linking Python 3 libraries.

gcc -pthread -B /scratch/sjn/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/sjn/anaconda/lib/**python3.6**/site-packages/numpy/core/include -Iinclude -I/usr/include/eigen3 -I/scratch/sjn/anaconda/include/**python3.6m** -c krahenbuhl2013.cpp -o build/temp.linux-x86_64-3.6/krahenbuhl2013.o

You need to figure out how to configure Anaconda as Python 2. I don't use Anaconda so I can't help with that.

**Comment by monajalal** [comment]
Ok, this issue was totally from my side. Even though I was running it with Python2, but my sys default was Python3, so I changed it in ~/.bash_profile and did the make clean and make and didn't even need to rename the file as it was created as krahenbuhl2013.so
It was linking stuff with Python3 in the make. Beautiful results and thanks for great work. I am sure many people in the community will benefit from this.
<img width="517" alt="screen shot 2017-12-02 at 5 02 07 pm" src="https://user-images.githubusercontent.com/1892917/33520118-8ec0fb44-d782-11e7-988a-c0a3e07919fd.png">

**Comment by paulu** [comment]
That's great!

Also, I just pushed some new CRF parameters that give sharper boundaries with the new code. Please pull and try those.

**Comment by monajalal** [comment]
Confirming that it worked way more smoothly. Thanks for updating the CRF parameters.
<img width="515" alt="screen shot 2017-12-02 at 5 21 35 pm" src="https://user-images.githubusercontent.com/1892917/33520273-ad4db09a-d785-11e7-924a-94aeb96b9880.png">
